### ISSUE TITLE
关于JAVA_HOME与ENABLED_DUMP_CORE

### ISSUE THREAD

**Issue by ciaranchen** [cas-bigdatalab/ambari-impala-service#3]
我们使用了这个项目在ambari上安装impala。但是遇到了一些问题：

- 首先是写在 `/etc/default/bigtop-utils`里的`JAVA_HOME`为何固定了是`/usr/jdk64`？我想在脚本中应该可以根据用户本身的`JAVAHOME`环境变量来做出改变。

- 另一个是关于 `package/templates/impala.j2`这个文件中的`ENABLE_CORE_DUMPS=false`。在impala日志中出现的错误信息如下：

```
Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
```

然后根据[这个网址](https://stackoverflow.com/questions/44116938/enable-saving-core-in-impala)，提示我们应将`ENABLE_CORE_DUMPS=false`改为`ENABLE_CORE_DUMPS=true`才能看到错误提示。我想知道这个变量有什么特殊的意义吗？而且在每次运行之前都进行一次配置文件的重新写入是否有意义？

如果能获得允许的话，我希望能向你们提一个pull request。

**Comment by ciaranchen** [comment]
另外，由于cdh仍在更新，在README中的网址也应从 

```
https://archive.cloudera.com/cdh5/redhat/6/x86_64/cdh/5/
```

变动到

```
https://archive.cloudera.com/cdh5/redhat/6/x86_64/cdh/5.8.0/
```

否则没法从此处获得下面所列的包文件

**Comment by ciaranchen** [comment]
再另：

`README` 中的包不能从url中获取，因为是el7的（也即需要在`/redhat/7/`中才能获得），请更正。

**Comment by excelwang** [comment]
Thanks for your feedback and pull request  #4 ! This issue is fixed at commit https://github.com/cas-bigdatalab/ambari-impala-service/commit/6c92206b1648295846f25b0bbbccc19045f4f44f .
